### PR TITLE
Mobile tabs

### PR DESCRIPTION
**Pull request by bchavet**
Removes text and pins tabs to the top of the screen for mobile

### CODE REVIEW

**Comment by jillmoreno** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr8-xq3afni2frdank6ssoaxmkgja65g7jbe.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5f0bddbb5e6fe7dd44eaea8e

**Comment by bchavet** [comment]
Hrm, the tabs are a little...stretchy in safari. Don't merge this until I get a chance to look at that. I'm calling it a night now, though.

Screen Shot 2020-07-12 at 11 08 57 PM

**Comment by jillmoreno** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr8-xq3afni2frdank6ssoaxmkgja65g7jbe.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5f0bddbb5e6fe7dd44eaea8e

**Comment by bchavet** [comment]
ok, that wasn't so bad. This is ready for review/merge

**Comment by jillmoreno** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr8-xq3afni2frdank6ssoaxmkgja65g7jbe.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5f0bddbb5e6fe7dd44eaea8e

**Pull request merged**
